# title: My Landing Page
# description: QuPath is cross-platform, user-friendly open source software for digital pathology and whole slide image analysis, written using JavaFX.  QuPath has also been designed to be developer-friendly, and combines an extensible design with powerful scripting tools.
# # repository: qupath/qupath.github.io
# url: "finglis.github.io"

# qupath_version: "0.4.3"

# # theme: my-landing-page-theme
# # remote_theme: finglis/finglis.github.io
# theme: finglis.github.io

# permalink: pretty
